import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faDatabase } from "@fortawesome/free-solid-svg-icons";
import {
  faHtml5,
  faCss3Alt,
  faJsSquare,
  faReact,
  faNode,
  faSass,
  faPhp,
  faPython,
  faXing,
  faSquarespace,
  faThemeco,
  faWordpressSimple,
  faBootstrap,
  faGripfire,
  faForumbee,
  faVuejs,
  faAngular,
  faJava,
  faLinux,
  faGitlab,
  faYarn,
  faGithub,
  faGitAlt,
  faWindows,
} from "@fortawesome/free-brands-svg-icons";

export const icons: any = {
  html: <FontAwesomeIcon icon={faHtml5} className="icon" />,
  css: <FontAwesomeIcon icon={faCss3Alt} className="icon" />,
  javascript: <FontAwesomeIcon icon={faJsSquare} className="icon" />,
  js: <FontAwesomeIcon icon={faJsSquare} className="icon" />,
  react: <FontAwesomeIcon icon={faReact} className="icon" />,
  node: <FontAwesomeIcon icon={faNode} className="icon" />,
  sass: <FontAwesomeIcon icon={faSass} className="icon" />,
  mongo: <FontAwesomeIcon icon={faDatabase} className="icon" />,
  sql: <FontAwesomeIcon icon={faDatabase} className="icon" />,
  nosql: <FontAwesomeIcon icon={faDatabase} className="icon" />,
  php: <FontAwesomeIcon icon={faPhp} className="icon" />,
  python: <FontAwesomeIcon icon={faPython} className="icon" />,
  express: <FontAwesomeIcon icon={faXing} className="icon" />,
  typescript: <FontAwesomeIcon icon={faSquarespace} className="icon" />,
  next: <FontAwesomeIcon icon={faThemeco} className="icon" />,
  tailwind: <FontAwesomeIcon icon={faGripfire} className="icon" />,
  bootstrap: <FontAwesomeIcon icon={faBootstrap} className="icon" />,
  jquery: <FontAwesomeIcon icon={faForumbee} className="icon" />,
  vue: <FontAwesomeIcon icon={faVuejs} className="icon" />,
  wordpress: <FontAwesomeIcon icon={faWordpressSimple} className="icon" />,
  angular: <FontAwesomeIcon icon={faAngular} className="icon" />,
  java: <FontAwesomeIcon icon={faJava} />,
  linux: <FontAwesomeIcon icon={faLinux} />,
  windows: <FontAwesomeIcon icon={faWindows} />,
  gitlab: <FontAwesomeIcon icon={faGitlab} />,
  github: <FontAwesomeIcon icon={faGithub} />,
  git: <FontAwesomeIcon icon={faGitAlt} />,
  yarn: <FontAwesomeIcon icon={faYarn} />,
};
